---
name: Continuous Deliver

on:
  push:
    branches: ["main"]

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulating CD
        uses: actions/upload-artifact@v4
        with:
          name: project.zip
          path: main.js

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: project.zip
      - name: Display structure of downloaded files
        run: ls -R